/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7fce9fd6-aed3-4619-9dda-26473672bcd8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_d7ctK3es0",
    "aws_user_pools_web_client_id": "35mabjjip8habgkflkv7joo9a6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ioyckrnijnagnjq3utvcuc5vai.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x7pqahf4gbfj5b3j743gbixh24",
    "aws_user_files_s3_bucket": "boxie-image-storage132638-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
